name: axis_task
description: "TMDB Popular People - A Flutter app showing popular people from TMDB API"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Responsiveness
  flutter_screenutil: ^5.9.0
  flutter_launcher_icons: ^0.14.4

  # Localization
  intl: ^0.20.2

  # State Management & Architecture
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Network & API
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^6.1.4

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image Handling
  photo_view: ^0.15.0
  gallery_saver_plus: ^3.2.8
  permission_handler: ^12.0.1

  # UI Components
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0

  # JSON & Code Generation
  json_annotation: ^4.8.1

  # Development Tools
  device_preview: ^1.3.1
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.3
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/